import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Account from "./Account";
import Navbar from "./Navbar";
const Layout = ({ children }) => {
  const [toggle, setToggle] = useState(false);

  return (
    <div className="block">
      <Head>
        <title>Titanium Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar handleToggle={() => setToggle(true)} />
      <main className="min-h-screen">
        <Account toggle={toggle} handleToggle={() => setToggle(false)} />
        {children}
        <div className="py-28 mt-6 bg-gradient-to-br from-purple-50 via-violet-100 to-blue-50">
          <div className="text-center w-10/12 md:w-3/4 lg:w-2/3 xl:w-1/2 mx-auto">
            <h1 className="text-4xl font-bold pb-2">
              Become a member for free
            </h1>
            <p className="text-lg text-gray-700 pb-2">
              Sign up to receive notifications and be able to comment and
              discuss on posts
            </p>
            <button
              onClick={() => setToggle(true)}
              className="py-4 bg-yellow-500 mt-4 px-4 rounded-lg ring-2 ring-white text-white font-medium"
            >
              Register your account
            </button>
          </div>
        </div>
      </main>
      <footer className="h-16 text-2xl bg-purple-700 text-white font-medium flex items-center justify-center">
        Titanium. All Rights Reserved
      </footer>
    </div>
  );
};

export default Layout;
