import Head from "next/head";
import Image from "next/image";
import Navbar from "./Navbar";
const Layout = ({ children }) => {
  return (
    <div className="block">
      <Head>
        <title>Titanium Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="min-h-screen">{children}</main>
      <footer className="h-16 text-2xl bg-purple-700 text-white font-medium flex items-center justify-center">
        Titanium. All Rights Reserved
      </footer>
    </div>
  );
};

export default Layout;
